### ISSUE TITLE
Clase Point - Establecer los límites posibles

### ISSUE THREAD

**Issue by gmunumel** [gmunumel/IWVG.SwC.Gabriel.Munumel#1]
Para la clase `Point` se desea restringir los límites posibles para la coordenada `x = [ 0..100 ]` y para la coordenada `y = -10..+10` 

> Tiempo estimado 1 día

Para mas información: [Clase Point](https://github.com/gmunumel/IWVG.SwC.Gabriel.Munumel/wiki/Clase-Point)

**Comment by dianagtf** [comment]
Clase Point modificada

**Comment by gmunumel** [comment]
Por favor agregar los test :)

**Comment by dianagtf** [comment]
Test añadido

**Comment by dianagtf** [comment]
Se añade test para una cobertura más amplia que abarque también los límites no válidos para el punto
