### ISSUE TITLE
Clase User - Presentar nombre en mayúsculas

### ISSUE THREAD

**Issue by gmunumel** [gmunumel/IWVG.SwC.Gabriel.Munumel#2]
Para la clase `User` se desea presentar el nombre en mayúsculas. Usar `String.toUpperCase()`.

> Tiempo estimado 1 día

Para mas información: [Clase User](https://github.com/gmunumel/IWVG.SwC.Gabriel.Munumel/wiki/Clase-User)

**Comment by Webkova** [comment]
Creado método userNameToUpperCase() en la clase User.
Creada clase UserTest para probar testUserNameToUpperCase()
