### ISSUE TITLE
Clase DecimalCollection - Incluir método menor

### ISSUE THREAD

**Issue by gmunumel** [gmunumel/IWVG.SwC.Gabriel.Munumel#3]
Para la clase `DecimalCollection` se desea incluir método `menor`. Tomar como referencia método `higher()`. 

> Tiempo estimado 1 día

Para mas información: [Clase DecimalCollection](https://github.com/gmunumel/IWVG.SwC.Gabriel.Munumel/wiki/Clase-DecimalCollection)

**Comment by xavism** [comment]
Done!
