### ISSUE TITLE
Clase Fraction - Incluir método como isPropia

### ISSUE THREAD

**Issue by gmunumel** [gmunumel/IWVG.SwC.Gabriel.Munumel#4]
Para la clase `Fraction` se desea incluir método `isPropia`. Las fracciones propias son aquellas cuyo numerador es menor que el denominador, y las fracciones impropias el resto.

> Tiempo estimado 1 día

Para mas información: [Clase Fraction](https://github.com/gmunumel/IWVG.SwC.Gabriel.Munumel/wiki/Clase-Fraction)

**Comment by Webkova** [comment]
Creado método isPropia y añadido testIsPropia() en FractionTest
