### ISSUE TITLE
Clase Fraction - Incluir el método isEquivalente

### ISSUE THREAD

**Issue by gmunumel** [gmunumel/IWVG.SwC.Gabriel.Munumel#5]
Para la clase `Fraction` se desea incluir el método `isEquivalente`. Dos fracciones son equivalentes cuando el producto de extremos es igual al producto de medios.

> Tiempo estimado 1 día

Para mas información: [Clase Fraction](https://github.com/gmunumel/IWVG.SwC.Gabriel.Munumel/wiki/Clase-Fraction)

**Comment by dianagtf** [comment]
Se ha añadido el método isEquivalente

**Comment by gmunumel** [comment]
Por favor agregar los test :)

**Comment by dianagtf** [comment]
Test añadido para issue#05
