### ISSUE TITLE
Clase Fraction - Incluir método mayor

### ISSUE THREAD

**Issue by gmunumel** [gmunumel/IWVG.SwC.Gabriel.Munumel#6]
Para la clase `Fraction` se desea incluir el método para comparar fracciones: `mayor`.

> Tiempo estimado 1 día

Para mas información: [Clase Fraction](https://github.com/gmunumel/IWVG.SwC.Gabriel.Munumel/wiki/Clase-Fraction)

**Comment by gmunumel** [comment]
Por favor agregar los test :)

**Comment by xavism** [comment]
Done
